# Generated by Django 3.2.24 on 2024-02-23 09:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=4)),
                ('name', models.CharField(max_length=10)),
                ('default_accounting_type', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], default='debit', max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JournalEntryLines',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accounting_date', models.DateTimeField(auto_now_add=True)),
                ('state', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], default='debit', max_length=10)),
                ('description', models.TextField()),
                ('reconciled', models.BooleanField(default=True)),
                ('amount', models.FloatField(default=0.0)),
                ('accounting_type', models.CharField(choices=[('draft', 'Draft'), ('booked', 'Booked')], default='draft', max_length=10)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.account')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.currency')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
